### ISSUE TITLE
Issue when having a Bard with sets of multiple fields

### ISSUE THREAD

**Issue by kennyhorna** [edalzell/statamic-blade#15]
Hey, great work by the way. This package make it a little bit easier the way to start working with Statamic.

### The current problem

The issue is the following while working with `Bard` elements: Currently, just the first value instance of Value is included in the payload of each set under the key `content`:

```php
# Edalzell\Blade\Directive\Bard

private function convertFromValueToArray(array $set)
{
    return [
        'type' => Arr::get($set, 'type'),
        'content' => $this->getFirstValueAsRaw($set), // <----
    ];
}

private function getFirstValueAsRaw($set)
{
    return Arr::first($set, fn ($value) => $value instanceof Value)->raw();
}                ^^^
```

### Use case

I'm rebuilding my blog but now with Statamic. Given that the main content are articles, I thought it'd be nice to be able to render blade components inside the body of the article, like a related article, a newsletter form, etc. That's why I though of making use of a Bard to define sets inside it with all the cases to properly render them.

As you can see in the following yaml (simplified to make it easy to read), my `blade_component` set has a `name` (text) and `parameters` (array). 

```yaml
title: Pages
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: content
        field:
          always_show_set_button: false
          sets:
            blade_component:
              display: 'Blade Component'
              fields:
                -
                  handle: name
                  field:
                    input_type: text
                    display: Name
                    type: text
                    icon: text
                    listable: true
                    validate:
                      - required
                -
                  handle: parameters
                  field:
                    mode: dynamic
                    display: Parameters
                    type: array
                    icon: array
                    listable: hidden
```

Another case could be for a Image set when trying to group in a set the source, alignment, and size options.

Under the current implementation, this data would be not possible to be passed to the view.
