### ISSUE TITLE
Issues rendering a Bard element within a replicator

### ISSUE THREAD

**Issue by canastro** [edalzell/statamic-blade#45]
Having the following data:
```yaml
tabs:
  -
    title: 'Excellent Service'
    description:
      -
        type: paragraph
        content:
          -
            type: text
            text: 'My Content'
    type: items
    enabled: true
  - ...
 ```

Where tabs is a replicator and description is a bard element.

When I try to render it as:

```blade
    @foreach($joint_comission_tabs as $tab)
    <div>
            <h3 class="text-2xl text-primary mb-3">{{$tab['title']}}</h3>
            <p class="mb-4">
                {!! $tab['description'] !!}
            </p>
    </div>
    @endforeach
```

I face the following error:

```
Array to string conversion (View: /Users/rows/dev/vicam/omni/resources/views/about.blade.php)
```

Just to provide a bit more detail:
- any other bard element I have on the same page that is at the root level (ie. not part of a replicator) is working just fine.
- this route is a statamic page/entry

**Comment by edalzell** [comment]
Can I see the blueprint please?

**Comment by canastro** [comment]
Sure:

```yaml
title: 'About Us'
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
  joint_comission:
    display: 'Joint Comission'
    fields:
      -
        handle: joint_comission_title
        field:
          input_type: text
          antlers: false
          display: Title
          type: text
          icon: text
          listable: hidden
          validate:
            - required
      -
        handle: joint_comission_description
        field:
          always_show_set_button: false
          buttons:
            - h2
            - h3
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - removeformat
            - quote
            - anchor
            - image
            - table
          save_html: false
          toolbar_mode: fixed
          link_noopener: false
          link_noreferrer: false
          target_blank: false
          reading_time: false
          fullscreen: true
          allow_source: true
          enable_input_rules: true
          enable_paste_rules: true
          display: Description
          type: bard
          icon: bard
          listable: hidden
          validate:
            - required
      -
        handle: joint_comission_tabs
        field:
          collapse: false
          sets:
            items:
              display: items
              fields:
                -
                  handle: title
                  field:
                    input_type: text
                    antlers: false
                    display: Title
                    type: text
                    icon: text
                    listable: hidden
                    validate:
                      - required
                -
                  handle: description
                  field:
                    antlers: false
                    display: Description
                    type: textarea
                    icon: textarea
                    listable: hidden
                -
                  import: call_to_action_link
                  prefix: joint_comission_
          display: Tabs
          type: replicator
          icon: replicator
          listable: hidden
  ```

The one not working is for: joint_comission > joint_comission_tabs > description:
